### ISSUE TITLE
Malloovia doesn't work with the latest version of PuLP

### ISSUE THREAD

**Issue by jentrialgo** [asi-uniovi/malloovia#18]
Current version of PuLP generates an execption in line 798 of lpsolver.py, which has this:

        lp.status, values, reducedCosts, shadowPrices, slacks = self.readsol_LP(
            tmpSol, lp, lp.variables()
        )

I think that the problem is that readsol_LP now returns an extra value, lp.sol_status. Therefore, the fix would be to change it to this:

        lp.status, values, reducedCosts, shadowPrices, slacks, lp.sol_status = self.readsol_LP(
            tmpSol, lp, lp.variables()
        )

**Comment by jldiaz** [comment]
Fixed in branch "fix" (2f1eb9b4b18668ae020328b8b9885bc1a41724e0). Will be active in next release 2.2.0
